trigger:
- main
pool:
  name: 'Default'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npx ng build telemetry-hub --configuration=production
  displayName: 'npm install and build telemetry-hub'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist/telemetry-hub/browser'
    ArtifactName: 'drop'
    publishLocation: 'Container'
